### ISSUE TITLE
Cannot build with go 1.26rc2

### ISSUE THREAD

**Issue by clin1234** [dunglas/mercure#1155]
```
mercure.exe: can't install github.com/dunglas/mercure/cmd/mercure:
# github.com/dunglas/mercure/cmd
go\pkg\mod\github.com\dunglas\mercure@v0.21.6\cmd\root.go:23:11: undefined: mercure.Start
go\pkg\mod\github.com\dunglas\mercure@v0.21.6\cmd\root.go:40:11: undefined: mercure.InitConfig
go\pkg\mod\github.com\dunglas\mercure@v0.21.6\cmd\root.go:44:10: undefined: mercure.SetFlags
```

**Comment by dunglas** [comment]
Fixed in the last release.
